version: "3.8"
services:
  my-nginx:
    build:
      context: ./my-nginx
    ports:
      - "8080:80"

  my-next-app:
    environment:
      REDIS_HOST: my-redis
    build:
      context: ./my-next-app

  my-redis:
    image: "bitnami/redis:latest"
    environment:
      REDIS_PASSWORD: a
